{% set name = "pins" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pins-{{ version }}.tar.gz
  sha256: 6d209dfc97a1a19d0ed7f364341d1ae76739a2776cb127a18b307c64a1c4b4a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - databackend >=0.0.3
    - typing_extensions
    - python >={{ python_min }}
    - fsspec >=2022.2
    - pyyaml >=3.13
    - python-xxhash >=1
    - pandas >=0.23
    - jinja2 >=2.10
    - joblib >=0.12
    - importlib-metadata >=4.4
    - importlib-resources >=1.3
    - appdirs <2
    - humanize >=1
    - requests

test:
  imports:
    - pins
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rstudio/pins-python
  summary: Publish data sets, models, and other python objects, making it easy to share them across projects and with your colleagues.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
