{% set name = "pins" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pins-{{ version }}.tar.gz
  sha256: df8d7d92d5dc1696964a471cafbe780a667ba324777c15bd6ab8d01815474339

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - appdirs <2.0.0
    - fsspec >=0.8.0,<2023.9.0
    - humanize >=1.0.0
    - importlib-metadata >=4.4
    - importlib-resources >=1.3
    - jinja2 >=2.10.0
    - joblib >=0.12.0
    - pandas >=0.23.0
    - python >=3.7
    - pyyaml >=3.13
    - requests
    - python-xxhash >=1.0.0

test:
  imports:
    - pins
  requires:
    - pip

about:
  home: https://github.com/rstudio/pins-python
  summary: Publish data sets, models, and other python objects, making it easy to share them across projects and with your colleagues.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
